/* CounciLLM local authentication. No network, tokens, passwords, or recovery codes are persisted. */
(() => {
  'use strict';
  const DB_NAME='councillm-auth', STORE='account', KEY='local-account', ITERATIONS=310000;
  const root=document.getElementById('auth-gate');
  let attempts=0, lockUntil=0, recoveryPlaintext='';
  const encoder=new TextEncoder();
  const bytesTo64=a=>btoa(String.fromCharCode(...a));
  const from64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
  const random=length=>{const value=new Uint8Array(length);crypto.getRandomValues(value);return value;};
  const equal=(a,b)=>{if(a.length!==b.length)return false;let result=0;for(let i=0;i<a.length;i++)result|=a[i]^b[i];return result===0;};
  async function derive(secret,salt,iterations=ITERATIONS){
    const key=await crypto.subtle.importKey('raw',encoder.encode(secret),'PBKDF2',false,['deriveBits']);
    return new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt,iterations},key,256));
  }
  function db(){return new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,1);request.onupgradeneeded=()=>request.result.createObjectStore(STORE,{keyPath:'id'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(new Error('Persistent local storage is unavailable.'));request.onblocked=()=>reject(new Error('Close other CounciLLM tabs before changing the local account.'));});}
  async function getAccount(){const database=await db();return new Promise((resolve,reject)=>{const request=database.transaction(STORE,'readonly').objectStore(STORE).get(KEY);request.onsuccess=()=>resolve(request.result||null);request.onerror=()=>reject(new Error('Could not read the local account.'));});}
  async function saveAccount(value){const database=await db();return new Promise((resolve,reject)=>{const request=database.transaction(STORE,'readwrite').objectStore(STORE).put(value);request.onsuccess=()=>resolve();request.onerror=()=>reject(new Error('Could not save the local account.'));});}
  async function removeAccount(){const database=await db();return new Promise((resolve,reject)=>{const request=database.transaction(STORE,'readwrite').objectStore(STORE).delete(KEY);request.onsuccess=()=>resolve();request.onerror=()=>reject(new Error('Could not remove the local account.'));});}
  function recoveryCode(){return [...random(20)].map(x=>x.toString(16).padStart(2,'0')).join('').toUpperCase().match(/.{1,5}/g).join('-');}
  function layout(title,subtitle,content){root.innerHTML=`<section class="auth-card" role="dialog" aria-modal="true" aria-labelledby="auth-title"><div class="auth-mark" aria-hidden="true"><svg width="40" height="40" viewBox="0 0 24 24" fill="currentColor" focusable="false"><path d="M12 2L13.5 9.5L21 11L13.5 12.5L12 20L10.5 12.5L3 11L10.5 9.5L12 2Z"/></svg></div><h1 id="auth-title">CounciLLM</h1><h2>${title}</h2><p class="auth-subtitle">${subtitle}</p>${content}<p class="auth-status" role="alert" aria-live="polite"></p><p class="auth-device-note">Stored only in this browser profile and device. Clearing browser site data removes this local account.</p></section>`;root.querySelector('input,button')?.focus();}
  function error(text){root.querySelector('.auth-status').textContent=text;}
  function passwordFields(includeUsername=false){return `${includeUsername?'<label>Username<input id="auth-username" autocomplete="username" maxlength="32" placeholder="3–32 letters, numbers, _ or -"></label>':''}<label>Password <span>12+ characters recommended</span><div class="password-field"><input id="auth-password" type="password" autocomplete="new-password"><button type="button" class="reveal" aria-label="Show password">Show</button></div></label>`;}
  function wireReveal(){root.querySelectorAll('.reveal').forEach(button=>button.onclick=()=>{const field=button.previousElementSibling;field.type=field.type==='password'?'text':'password';button.textContent=field.type==='password'?'Show':'Hide';});}
  function showSetup(){layout('Create your local account','This is a one-time setup. CounciLLM never sends your credentials anywhere.',`<form id="auth-form">${passwordFields(true)}<label>Confirm password<div class="password-field"><input id="auth-confirm" type="password" autocomplete="new-password"><button type="button" class="reveal" aria-label="Show confirmation password">Show</button></div></label><p class="auth-hint">Use a unique password with at least 12 characters. Your password is never stored in plaintext.</p><button class="auth-primary" type="submit">Create account</button></form>`);wireReveal();root.querySelector('#auth-form').onsubmit=async event=>{event.preventDefault();const username=root.querySelector('#auth-username').value.trim(),password=root.querySelector('#auth-password').value,confirm=root.querySelector('#auth-confirm').value;if(!/^[A-Za-z0-9_-]{3,32}$/.test(username))return error('Use 3–32 letters, numbers, underscores, or hyphens.');if(password.length<12)return error('Choose a password with at least 12 characters.');if(password!==confirm)return error('Passwords do not match.');try{if(await getAccount())return showLogin();const salt=random(16),recoverySalt=random(16);recoveryPlaintext=recoveryCode();await saveAccount({id:KEY,version:1,username,password:{salt:bytesTo64(salt),verifier:bytesTo64(await derive(password,salt)),iterations:ITERATIONS},recovery:{salt:bytesTo64(recoverySalt),verifier:bytesTo64(await derive(recoveryPlaintext,recoverySalt)),iterations:ITERATIONS},createdAt:new Date().toISOString()});showRecovery();}catch(e){error(e.message);}};}
  function showRecovery(){layout('Save your recovery code','This is the only way to reset a forgotten password offline.',`<div class="recovery-code" id="recovery-code">${recoveryPlaintext}</div><div class="recovery-actions"><button type="button" class="auth-secondary" id="copy-recovery">Copy recovery code</button><p class="auth-warning">CounciLLM cannot display this code again or recover it for you. Save it somewhere safe before continuing.</p><label class="auth-check"><input id="saved-recovery" type="checkbox"><span>I have saved my recovery code.</span></label><button class="auth-primary" id="finish-setup" disabled>Continue to login</button></div>`);root.querySelector('#copy-recovery').onclick=async()=>{try{await navigator.clipboard.writeText(recoveryPlaintext);error('Recovery code copied.');}catch{error('Copy is unavailable; record the displayed code manually.');}};const check=root.querySelector('#saved-recovery');check.onchange=()=>root.querySelector('#finish-setup').disabled=!check.checked;root.querySelector('#finish-setup').onclick=()=>{recoveryPlaintext='';showLogin('Account created. Sign in to unlock CounciLLM.');};}
  async function verify(account,secret,kind){const item=account[kind],actual=await derive(secret,from64(item.salt),item.iterations);return equal(actual,from64(item.verifier));}
  function throttle(){if(Date.now()<lockUntil){error(`Please wait ${Math.ceil((lockUntil-Date.now())/1000)} seconds before trying again.`);return true;}return false;}
  function fail(){attempts++;if(attempts>=3){lockUntil=Date.now()+Math.min(30000,(attempts-2)*2000);error('Authentication failed. Please wait briefly before trying again.');}else error('Authentication failed.');}
  function showLogin(message=''){layout('Unlock CounciLLM','Sign in locally to access this CounciLLM workspace.',`<form id="auth-form"><label>Username<input id="auth-username" autocomplete="username"></label>${passwordFields()}<button class="auth-primary" type="submit">Login</button></form><div class="auth-links"><button type="button" id="forgot-password">Forgot password?</button><button type="button" class="danger-link" id="delete-account">Delete account</button></div>`);wireReveal();if(message)error(message);root.querySelector('#auth-form').onsubmit=async event=>{event.preventDefault();if(throttle())return;try{const account=await getAccount();const username=root.querySelector('#auth-username').value.trim(),password=root.querySelector('#auth-password').value;if(!account||username!==account.username||!(await verify(account,password,'password')))return fail();attempts=0;unlock();}catch(e){error(e.message);}};root.querySelector('#forgot-password').onclick=showRecoveryVerify;root.querySelector('#delete-account').onclick=showDelete;}
  function showRecoveryVerify(){layout('Recover your password','Because CounciLLM is offline, use the recovery code saved during account setup.',`<form id="auth-form"><label>Recovery code<input id="recovery-input" autocomplete="off" spellcheck="false" placeholder="ABCDE-12345-…"></label><button class="auth-primary" type="submit">Verify recovery code</button><button class="auth-secondary" type="button" id="back-login">Back to login</button></form><p class="auth-hint">If you lose both your password and recovery code, CounciLLM cannot recover this account.</p>`);root.querySelector('#back-login').onclick=()=>showLogin();root.querySelector('#auth-form').onsubmit=async event=>{event.preventDefault();if(throttle())return;try{const account=await getAccount(),code=root.querySelector('#recovery-input').value.trim().toUpperCase();if(!account||!(await verify(account,code,'recovery')))return fail();attempts=0;showReset(account);}catch(e){error(e.message);}};}
  function showReset(account){layout('Choose a new password','Your recovery code was verified. Set a new local password.',`<form id="auth-form">${passwordFields()}<label>Confirm new password<div class="password-field"><input id="auth-confirm" type="password" autocomplete="new-password"><button type="button" class="reveal">Show</button></div></label><button class="auth-primary" type="submit">Save new password</button></form>`);wireReveal();root.querySelector('#auth-form').onsubmit=async event=>{event.preventDefault();const password=root.querySelector('#auth-password').value,confirm=root.querySelector('#auth-confirm').value;if(password.length<12)return error('Choose a password with at least 12 characters.');if(password!==confirm)return error('Passwords do not match.');try{const salt=random(16);account.password={salt:bytesTo64(salt),verifier:bytesTo64(await derive(password,salt)),iterations:ITERATIONS};await saveAccount(account);showLogin('Password updated. Sign in with your new password.');}catch(e){error(e.message);}};}
  function showDelete(){layout('Delete your local account','This permanently removes CounciLLM account credentials and CounciLLM workspace data from this device.',`<form id="auth-form"><label>Current password or recovery code<input id="delete-secret" type="password" autocomplete="off"></label><label class="auth-check"><input id="delete-recovery" type="checkbox"> I am using my recovery code instead of my password.</label><label class="auth-check"><input id="delete-confirm" type="checkbox"> I understand this cannot be undone.</label><button class="auth-danger" type="submit">Permanently delete account</button><button class="auth-secondary" type="button" id="back-login">Cancel</button></form>`);root.querySelector('#back-login').onclick=()=>showLogin();root.querySelector('#auth-form').onsubmit=async event=>{event.preventDefault();if(!root.querySelector('#delete-confirm').checked)return error('Confirm that deletion is permanent.');if(throttle())return;try{const account=await getAccount(),kind=root.querySelector('#delete-recovery').checked?'recovery':'password';if(!account||!(await verify(account,root.querySelector('#delete-secret').value,kind)))return fail();const response=await fetch('/api/account/data',{method:'DELETE'});if(!response.ok)throw new Error('Could not remove CounciLLM workspace data.');await removeAccount();attempts=0;showSetup();}catch(e){error(e.message);}};}
  function unlock(){root.classList.add('auth-unlocked');root.setAttribute('aria-hidden','true');document.body.classList.remove('auth-locked');window.councilBootstrap?.();}
  async function start(){if(!window.isSecureContext||!window.crypto?.subtle||!window.indexedDB){layout('Local storage unavailable','CounciLLM authentication requires IndexedDB and the browser Web Crypto API. Open the local app in a modern browser.','');return;}try{(await getAccount())?showLogin():showSetup();}catch(e){layout('Local storage unavailable',e.message,'');}}
  document.addEventListener('DOMContentLoaded',start,{once:true});
})();
